theme: jekyll-theme-minimal
title: The role of women in the film industry - what is behind the prejudices?
description: Analysis of 42000 film movies
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
